/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create User Route */
        post: operations["create_user_route_api_v1_admin_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Agent Key Route */
        post: operations["create_agent_key_route_api_v1_admin_api_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot */
        get: operations["snapshot_api_v1_market_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/expiries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Expiries */
        get: operations["expiries_api_v1_market_expiries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/chain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chain */
        get: operations["chain_api_v1_market_chain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/candles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Candles */
        get: operations["candles_api_v1_market_candles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/depth/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Depth */
        get: operations["depth_api_v1_market_depth__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Portfolios */
        get: operations["list_portfolios_api_v1_portfolios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolio_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portfolio */
        get: operations["get_portfolio_api_v1_portfolios__portfolio_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Orders */
        get: operations["get_orders_api_v1_orders_get"];
        put?: never;
        /** Submit Order */
        post: operations["submit_order_api_v1_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Positions */
        get: operations["positions_api_v1_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions/{position_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close */
        post: operations["close_api_v1_positions__position_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/funds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Funds */
        get: operations["get_funds_api_v1_funds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analytics */
        get: operations["analytics_api_v1_analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/signals/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Signal */
        get: operations["latest_signal_api_v1_signals_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Signals */
        get: operations["list_signals_api_v1_signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Agent Order */
        post: operations["agent_order_api_v1_agent_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/funds/{portfolio_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent Funds */
        get: operations["agent_funds_api_v1_agent_funds__portfolio_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/signals/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent Latest Signal */
        get: operations["agent_latest_signal_api_v1_agent_signals_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/positions/{position_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Agent Close */
        post: operations["agent_close_api_v1_agent_positions__position_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentKeyResponse */
        AgentKeyResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Key Prefix */
            key_prefix: string;
            /** Scopes */
            scopes: string[];
            /** Secret */
            secret?: string | null;
        };
        /** AnalyticsPoint */
        AnalyticsPoint: {
            /** Label */
            label: string;
            /** Value */
            value: number;
        };
        /** AnalyticsResponse */
        AnalyticsResponse: {
            /** Portfolio Id */
            portfolio_id: string;
            /** Total Orders */
            total_orders: number;
            /** Filled Orders */
            filled_orders: number;
            /** Win Rate */
            win_rate: number;
            /** Realized Pnl */
            realized_pnl: number;
            /** Unrealized Pnl */
            unrealized_pnl: number;
            /** Total Equity */
            total_equity: number;
            /** Equity Curve */
            equity_curve: components["schemas"]["AnalyticsPoint"][];
            /** Pnl By Day */
            pnl_by_day: components["schemas"]["AnalyticsPoint"][];
        };
        /** Candle */
        Candle: {
            /** Time */
            time: number;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /**
             * Volume
             * @default 0
             */
            volume: number;
        };
        /** CandleResponse */
        CandleResponse: {
            /** Timeframe */
            timeframe: string;
            /** Candles */
            candles: components["schemas"]["Candle"][];
            /** Source */
            source: string;
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
        };
        /** CreateAgentKeyRequest */
        CreateAgentKeyRequest: {
            /** Name */
            name: string;
            /** Scopes */
            scopes?: string[];
        };
        /** CreateUserRequest */
        CreateUserRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Display Name */
            display_name: string;
            /** Password */
            password: string;
            /**
             * Role
             * @default trader
             * @enum {string}
             */
            role: "admin" | "trader" | "viewer";
        };
        /** FundsResponse */
        FundsResponse: {
            /** Portfolio Id */
            portfolio_id: string;
            /** Cash Balance */
            cash_balance: number;
            /** Blocked Margin */
            blocked_margin: number;
            /** Blocked Premium */
            blocked_premium: number;
            /** Available Funds */
            available_funds: number;
            /** Realized Pnl */
            realized_pnl: number;
            /** Unrealized Pnl */
            unrealized_pnl: number;
            /** Total Equity */
            total_equity: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** App */
            app: string;
            /** Environment */
            environment: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MarketSnapshot */
        MarketSnapshot: {
            /**
             * Spot Symbol
             * @default NIFTY 50
             */
            spot_symbol: string;
            /** Spot */
            spot: number;
            /** Change */
            change: number;
            /** Change Pct */
            change_pct: number;
            /** Vix */
            vix?: number | null;
            /** Pcr */
            pcr?: number | null;
            /** Market Status */
            market_status: string;
            /** Expiries */
            expiries?: string[];
            /** Active Expiry */
            active_expiry?: string | null;
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /** Degraded Reason */
            degraded_reason?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** OptionChainResponse */
        OptionChainResponse: {
            snapshot: components["schemas"]["MarketSnapshot"];
            /** Rows */
            rows: components["schemas"]["OptionChainRow"][];
        };
        /** OptionChainRow */
        OptionChainRow: {
            /** Strike */
            strike: number;
            /** Is Atm */
            is_atm: boolean;
            call: components["schemas"]["OptionQuote"];
            put: components["schemas"]["OptionQuote"];
        };
        /** OptionQuote */
        OptionQuote: {
            /** Symbol */
            symbol: string;
            /** Security Id */
            security_id?: string | null;
            /** Strike */
            strike: number;
            /**
             * Option Type
             * @enum {string}
             */
            option_type: "CE" | "PE";
            /** Expiry */
            expiry: string;
            /** Ltp */
            ltp: number;
            /** Bid */
            bid?: number | null;
            /** Ask */
            ask?: number | null;
            /** Bid Qty */
            bid_qty?: number | null;
            /** Ask Qty */
            ask_qty?: number | null;
            /** Iv */
            iv?: number | null;
            /** Oi */
            oi?: number | null;
            /** Volume */
            volume?: number | null;
            /** Delta */
            delta?: number | null;
            /** Gamma */
            gamma?: number | null;
            /** Theta */
            theta?: number | null;
            /** Vega */
            vega?: number | null;
        };
        /** OrderRequest */
        OrderRequest: {
            /** Portfolio Id */
            portfolio_id: string;
            /** Symbol */
            symbol?: string | null;
            /** Expiry */
            expiry: string;
            /** Strike */
            strike: number;
            /**
             * Option Type
             * @enum {string}
             */
            option_type: "CE" | "PE";
            /**
             * Side
             * @enum {string}
             */
            side: "BUY" | "SELL";
            /**
             * Order Type
             * @enum {string}
             */
            order_type: "MARKET" | "LIMIT" | "SL" | "SL-M";
            /**
             * Product
             * @default NRML
             * @enum {string}
             */
            product: "NRML" | "MIS";
            /**
             * Validity
             * @default DAY
             * @constant
             */
            validity: "DAY";
            /**
             * Lots
             * @default 1
             */
            lots: number;
            /** Price */
            price?: number | null;
            /** Trigger Price */
            trigger_price?: number | null;
            /** Signal Id */
            signal_id?: string | null;
            /** Idempotency Key */
            idempotency_key?: string | null;
        };
        /** OrderSummary */
        OrderSummary: {
            /** Id */
            id: string;
            /** Portfolio Id */
            portfolio_id: string;
            /** Symbol */
            symbol: string;
            /** Expiry */
            expiry: string;
            /** Strike */
            strike: number;
            /**
             * Option Type
             * @enum {string}
             */
            option_type: "CE" | "PE";
            /**
             * Side
             * @enum {string}
             */
            side: "BUY" | "SELL";
            /**
             * Order Type
             * @enum {string}
             */
            order_type: "MARKET" | "LIMIT" | "SL" | "SL-M";
            /**
             * Product
             * @enum {string}
             */
            product: "NRML" | "MIS";
            /**
             * Validity
             * @constant
             */
            validity: "DAY";
            /** Lots */
            lots: number;
            /** Quantity */
            quantity: number;
            /** Price */
            price?: number | null;
            /** Trigger Price */
            trigger_price?: number | null;
            /** Status */
            status: string;
            /** Average Price */
            average_price?: number | null;
            /** Filled Quantity */
            filled_quantity: number;
            /** Premium Required */
            premium_required: number;
            /** Margin Required */
            margin_required: number;
            /** Charges */
            charges: number;
            /** Message */
            message?: string | null;
            /** Source */
            source: string;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /** Filled At */
            filled_at?: string | null;
        };
        /** PortfolioSummary */
        PortfolioSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Starting Cash */
            starting_cash: number;
            /** Cash Balance */
            cash_balance: number;
            /** Blocked Margin */
            blocked_margin: number;
            /** Blocked Premium */
            blocked_premium: number;
            /** Realized Pnl */
            realized_pnl: number;
            /** Available Funds */
            available_funds: number;
            /** Total Equity */
            total_equity: number;
        };
        /** PositionSummary */
        PositionSummary: {
            /** Id */
            id: string;
            /** Portfolio Id */
            portfolio_id: string;
            /** Symbol */
            symbol: string;
            /** Expiry */
            expiry: string;
            /** Strike */
            strike: number;
            /**
             * Option Type
             * @enum {string}
             */
            option_type: "CE" | "PE";
            /**
             * Product
             * @enum {string}
             */
            product: "NRML" | "MIS";
            /** Net Quantity */
            net_quantity: number;
            /** Lot Size */
            lot_size: number;
            /** Average Open Price */
            average_open_price: number;
            /** Last Price */
            last_price: number;
            /** Blocked Margin */
            blocked_margin: number;
            /** Realized Pnl */
            realized_pnl: number;
            /** Unrealized Pnl */
            unrealized_pnl: number;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
        };
        /** SignalResponse */
        SignalResponse: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Direction */
            direction: string;
            /** Confidence Label */
            confidence_label: string;
            /** Confidence Score */
            confidence_score: number;
            /** Trade Text */
            trade_text?: string | null;
            /** Strike */
            strike?: number | null;
            /** Option Type */
            option_type?: ("CE" | "PE") | null;
            /** Expiry */
            expiry?: string | null;
            /** Entry Low */
            entry_low?: number | null;
            /** Entry High */
            entry_high?: number | null;
            /** Target Price */
            target_price?: number | null;
            /** Stop Loss */
            stop_loss?: number | null;
            /** Index Target */
            index_target?: number | null;
            /** Index Stop */
            index_stop?: number | null;
            /** Is Actionable */
            is_actionable: boolean;
            /** Target Valid */
            target_valid: boolean;
            /** Stop Valid */
            stop_valid: boolean;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** TokenEnvelope */
        TokenEnvelope: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
            user: components["schemas"]["UserSummary"];
        };
        /** UserSummary */
        UserSummary: {
            /** Id */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Display Name */
            display_name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "trader" | "viewer";
            /** Is Active */
            is_active: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                lite_refresh?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                lite_refresh?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_route_api_v1_admin_users_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_agent_key_route_api_v1_admin_api_keys_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAgentKeyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentKeyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshot_api_v1_market_snapshot_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    expiries_api_v1_market_expiries_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chain_api_v1_market_chain_get: {
        parameters: {
            query?: {
                expiry?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptionChainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    candles_api_v1_market_candles_get: {
        parameters: {
            query?: {
                timeframe?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    depth_api_v1_market_depth__symbol__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_portfolios_api_v1_portfolios_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_api_v1_portfolios__portfolio_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_orders_api_v1_orders_get: {
        parameters: {
            query?: {
                portfolio_id?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_order_api_v1_orders_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    positions_api_v1_positions_get: {
        parameters: {
            query?: {
                portfolio_id?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_api_v1_positions__position_id__close_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_funds_api_v1_funds_get: {
        parameters: {
            query: {
                portfolio_id: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analytics_api_v1_analytics_get: {
        parameters: {
            query: {
                portfolio_id: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_signal_api_v1_signals_latest_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalResponse"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_signals_api_v1_signals_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_order_api_v1_agent_orders_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_funds_api_v1_agent_funds__portfolio_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_latest_signal_api_v1_agent_signals_latest_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalResponse"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_close_api_v1_agent_positions__position_id__close_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
